import fs from "fs";
import path from "path";
import crypto from "crypto";

// Fonction pour générer un secret aléatoire sécurisé
export function generateRandomSecret(length: number = 32): string {
    return crypto.randomBytes(length).toString('hex');
}

// Fonction pour générer un secret base64 (pour certaines clés)
export function generateBase64Secret(length: number = 32): string {
    return crypto.randomBytes(length).toString('base64');
}

// Fonction pour générer les fichiers .env
export function generateEnvFiles(projectName: string, backend: string, database: string): void {
    // Variables communes pour le backend
    const backendEnv: Record<string, string> = {
        // Secrets de sécurité
        JWT_SECRET: generateRandomSecret(64),
        JWT_REFRESH_SECRET: generateRandomSecret(64),

        // Configuration serveur
        PORT: "3000",
        NODE_ENV: "development",

        // Clés API (exemples)
        API_KEY: generateRandomSecret(32),
        ENCRYPTION_KEY: generateBase64Secret(32),
    };

    // Ajouter les variables de base de données selon le choix
    if (database === "PostgreSQL") {
        backendEnv.DATABASE_URL = "postgresql://user:password@localhost:5432/my_database";
        backendEnv.DB_HOST = "localhost";
        backendEnv.DB_PORT = "5432";
        backendEnv.DB_USER = "user";
        backendEnv.DB_PASSWORD = "password";
        backendEnv.DB_NAME = "my_database";
    } else if (database === "MariaDB") {
        backendEnv.DATABASE_URL = "mysql://user:password@localhost:3306/my_database";
        backendEnv.DB_HOST = "localhost";
        backendEnv.DB_PORT = "3306";
        backendEnv.DB_USER = "user";
        backendEnv.DB_PASSWORD = "password";
        backendEnv.DB_NAME = "my_database";
    } else if (database === "SQLite") {
        backendEnv.DATABASE_URL = "file:./dev.db";
    }

    // Variables spécifiques selon le backend
    if (backend.includes("nestjs")) {
        backendEnv.THROTTLE_TTL = "60";
        backendEnv.THROTTLE_LIMIT = "10";
    }

    // Générer le contenu du fichier .env backend
    const backendEnvContent = generateEnvContent(backendEnv, "Backend");
    fs.writeFileSync(path.join(projectName, "backend", ".env"), backendEnvContent);
    fs.writeFileSync(path.join(projectName, "backend", ".env.example"), generateEnvExampleContent(backendEnv, "Backend"));

    // Variables pour le frontend
    const frontendEnv: Record<string, string> = {
        VITE_API_URL: "http://localhost:3000/api",
        VITE_APP_NAME: projectName,
        VITE_APP_VERSION: "1.0.0",
    };

    const frontendEnvContent = generateEnvContent(frontendEnv, "Frontend");
    fs.writeFileSync(path.join(projectName, "frontend", ".env"), frontendEnvContent);
    fs.writeFileSync(path.join(projectName, "frontend", ".env.example"), generateEnvExampleContent(frontendEnv, "Frontend"));

    // Créer un .env à la racine pour docker-compose si nécessaire
    if (database !== "Aucune" && database !== "SQLite") {
        const rootEnv: Record<string, string> = {
            DB_USER: "user",
            DB_PASSWORD: "password",
            DB_NAME: "my_database",
        };
        if (database === "MariaDB") {
            rootEnv.DB_ROOT_PASSWORD = "root";
        }
        fs.writeFileSync(path.join(projectName, ".env"), generateEnvContent(rootEnv, "Docker"));
    }
}

// Fonction pour générer le contenu formaté du fichier .env
function generateEnvContent(vars: Record<string, string>, section: string): string {
    const timestamp = new Date().toISOString();
    let content = `# ═══════════════════════════════════════════════════════════════\n`;
    content += `# ${section} Environment Variables\n`;
    content += `# Generated by smash-cli on ${timestamp}\n`;
    content += `# ═══════════════════════════════════════════════════════════════\n\n`;

    // Grouper les variables par catégorie
    const securityVars: string[] = [];
    const serverVars: string[] = [];
    const dbVars: string[] = [];
    const apiVars: string[] = [];
    const appVars: string[] = [];

    for (const [key, value] of Object.entries(vars)) {
        const line = `${key}=${value}`;
        if (key.includes("SECRET") || key.includes("KEY") || key.includes("PASSWORD")) {
            securityVars.push(line);
        } else if (key.includes("DB") || key.includes("DATABASE")) {
            dbVars.push(line);
        } else if (key.includes("PORT") || key.includes("HOST") || key.includes("NODE_ENV")) {
            serverVars.push(line);
        } else if (key.includes("API") || key.includes("URL")) {
            apiVars.push(line);
        } else {
            appVars.push(line);
        }
    }

    if (securityVars.length > 0) {
        content += `# 🔐 Security\n`;
        content += securityVars.join("\n") + "\n\n";
    }

    if (serverVars.length > 0) {
        content += `# 🖥️ Server Configuration\n`;
        content += serverVars.join("\n") + "\n\n";
    }

    if (dbVars.length > 0) {
        content += `# 🗄️ Database\n`;
        content += dbVars.join("\n") + "\n\n";
    }

    if (apiVars.length > 0) {
        content += `# 🌐 API Configuration\n`;
        content += apiVars.join("\n") + "\n\n";
    }

    if (appVars.length > 0) {
        content += `# 📱 Application\n`;
        content += appVars.join("\n") + "\n\n";
    }

    return content;
}

// Fonction pour générer le .env.example (sans les valeurs sensibles)
function generateEnvExampleContent(vars: Record<string, string>, section: string): string {
    const timestamp = new Date().toISOString();
    let content = `# ═══════════════════════════════════════════════════════════════\n`;
    content += `# ${section} Environment Variables Example\n`;
    content += `# Copy this file to .env and fill in your values\n`;
    content += `# Generated by smash-cli on ${timestamp}\n`;
    content += `# ═══════════════════════════════════════════════════════════════\n\n`;

    for (const [key, value] of Object.entries(vars)) {
        // Masquer les valeurs sensibles
        if (key.includes("SECRET") || key.includes("KEY") || key.includes("PASSWORD")) {
            content += `${key}=your_${key.toLowerCase()}_here\n`;
        } else {
            content += `${key}=${value}\n`;
        }
    }

    return content;
}
